#! /bin/sh
### BEGIN INIT INFO
# Provides:          aasplashscreen
# Required-Start: networking ifupdown
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO


do_start () {
  # Shows splashscreen and show webinterface URI
  _IP=$(hostname -I) || true
  _IP=$(echo "${_IP}" | sed 's/[ \t]*$//')
  /usr/bin/fbi --noreadahead --timeout 10 -T 1 -noverbose --nocomments --autozoom --once /etc/pichannelorg.png /etc/pichannel.png &
  /usr/bin/convert /etc/pichannelorg.png -font FreeSans-Bold -pointsize 40 -gravity southwest -fill white -annotate +0+0 "http://$_IP/index.py" /etc/pichannel.png
  sleep 10
  exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: aasplashscreen [start|stop]" >&2
    exit 3
    ;;
esac

:
